"""Write <dir>/MANIFEST.json for a schedules directory: sha256, size and schedcheck verdict per JSON file.

Generated schedules from wave 8 on are not committed (they are 1-21 MB each and regenerated by each kernel's
schedule generator); the manifest records exactly what was validated.
usage: python3 scripts/schedule_manifest.py DIR [DIR ...]
"""

import hashlib
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEDCHECK = ROOT / "validator/target/release/schedcheck"

for d in map(Path, sys.argv[1:]):
    entries = []
    for f in sorted(d.glob("*.json")):
        if f.name == "MANIFEST.json":
            continue
        run = subprocess.run([str(SCHEDCHECK), str(f)], capture_output=True, text=True, timeout=600)
        verdict = "ACCEPT" if run.returncode == 0 else "REJECT"
        entries.append({"file": f.name, "bytes": f.stat().st_size,
                        "sha256": hashlib.sha256(f.read_bytes()).hexdigest(), "schedcheck": verdict})
        print(f"{verdict} {f}")
    manifest = {"validator": "validator/target/release/schedcheck (Schedule IR v1)", "schedules": entries,
                "note": "Schedule JSONs are regenerated by this kernel's schedule generator; not committed."}
    (d / "MANIFEST.json").write_text(json.dumps(manifest, indent=1) + "\n")
    bad = [e["file"] for e in entries if e["schedcheck"] != "ACCEPT"]
    print(f"{d}: {len(entries)} schedules, {len(bad)} rejected {bad}")
