"""Write <dir>/MANIFEST.json for a schedules directory: sha256, size and schedcheck verdict per JSON file.

Generated schedules from wave 8 on are not committed (they are 1-21 MB each and regenerated by each kernel's
schedule generator); the manifest records exactly what was validated.
usage: python3 scripts/schedule_manifest.py [--check] DIR [DIR ...]
"""

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEDCHECK = ROOT / "validator/target/release/schedcheck"

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true', help='Verify committed hashes and ACCEPT verdicts without rewriting manifests')
parser.add_argument('directories', type=Path, nargs='+')
args = parser.parse_args()

for d in args.directories:
    manifest_path = d / "MANIFEST.json"
    expected = json.loads(manifest_path.read_text()) if args.check else None
    entries = []
    for f in sorted(d.glob("*.json")):
        if f.name == "MANIFEST.json":
            continue
        run = subprocess.run([str(SCHEDCHECK), str(f)], capture_output=True, text=True, timeout=600)
        verdict = "ACCEPT" if run.returncode == 0 else "REJECT"
        entries.append({"file": f.name, "bytes": f.stat().st_size,
                        "sha256": hashlib.sha256(f.read_bytes()).hexdigest(), "schedcheck": verdict})
        print(f"{verdict} {f}")
    manifest = {"validator": "validator/target/release/schedcheck (Schedule IR v1)", "schedules": entries,
                "note": "Schedule JSONs are regenerated by this kernel's schedule generator; not committed."}
    bad = [e["file"] for e in entries if e["schedcheck"] != "ACCEPT"]
    if args.check:
        if entries != expected["schedules"]:
            raise SystemExit(f"{d}: regenerated schedules differ from committed manifest (file list, bytes, sha256 or verdict)")
        if bad:
            raise SystemExit(f"{d}: manifest matches but schedules are rejected: {bad}")
        print(f"{d}: {len(entries)} schedules match committed sha256 and ACCEPT verdicts")
    else:
        manifest_path.write_text(json.dumps(manifest, indent=1) + "\n")
        print(f"{d}: {len(entries)} schedules, {len(bad)} rejected {bad}")
